server:
  port: 3600
database:
  host: database
  port: 5432
  user: postgres
  password: root
  dbname: envocc_services
  timezone: Asia/Bangkok
jwt:
  access: aassddff
  refresh: zzxxccvv
  access_exp: 300
  refresh_exp: 3600
